config/routes.rb
Rails.application.routes.draw do

  devise_for :climbers, controllers: { registrations: "climbers/registrations" }

  devise_scope :climber do
    get 'public_climbers' => 'climbers/registrations#public_climbers'
  end

  resources :trainings, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :finishes, only: [:index, :new, :create, :edit, :update, :destroy]

  root 'main#index'
  get 'development' => 'main#development'

end

app/models/training.rb
class Training < ActiveRecord::Base
  belongs_to :climber
  has_many :finishes, dependent: :destroy

  def self.climber_id trainging_id
  	find(trainging_id).climber_id
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :authenticate_climber!, :except => [:index]
   
  # request a climber_id 
  def index
  	param! :climber_id,           Integer, required: true

    is_public = climber_public? params[:climber_id]
    authenticate_climber! unless is_public
    @is_owner = belong_to_current_user? params[:climber_id]

    if @is_owner || is_public
      climber = Climber.find(params[:climber_id])
    	@trainings = climber.trainings.order(date: :desc).decorate
    end

    respond_to do |format|
      format.html { redirect_to :root, notice: 'not authoriz to view the request records.' } unless (@is_owner || is_public)
      format.html
    end
  end

  def new
  	@training = Training.new
  end

  def edit
    @training = Training.find(params[:id])
  end

  def create

    param! :training, Hash do |t|
      t.param! :date, Date, required: true
    end

    @training = Training.new(training_params.merge(climber_id: current_climber.id))

    respond_to do |format|
      if @training.save
        format.html { redirect_to new_finish_path(training_id: @training.id), notice: 'climbing record was successfully created.'}
      else
        format.html { redirect_to :back, notice: 'climbing record was not successfully created.' }
      end
    end
  end

  def update
    @is_owner = Training.find(params['id'].to_i).climber_id == current_climber.id

    @training = Training.find(params[:id])
    respond_to do |format|

      if !@is_owner
        format.html { redirect_to :root, notice: 'not authoriz to update the request record.' }
      elsif @training.update_attributes(training_params)
        format.html { redirect_to finishes_path(training_id: @training.id), notice: 'training record update success' }
      else
        format.html { redirect_to :back, notice: 'training record update failed, please try again.' }
      end

    end
  end

  def destroy
    @is_owner = Training.find(params['id'].to_i).climber_id == current_climber.id

    Training.find(params[:id]).destroy if @is_owner
    respond_to do |format|
      if @is_owner
        format.html { redirect_to :back, notice: 'training record delete success' }
      else
        format.html { redirect_to :root, notice: 'not authoriz to delete the request record.' }
      end
    end
  end

  private 

  def training_params
    params.require(:training).permit(:date)
  end
end

app/views/trainings/_form.html.erb
<%= form_for(@training) do |f| %>

  <% if @training.errors.any? %>
    <div>
      <h2><%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:</h2>
      <ul>
      <% @training.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>
  <div class="actions">
    <%= f.submit "Enter finishes for this training"%>
  </div>
<% end %>

app/views/trainings/_training.html.erb
<tr>
	<td> <%= training.climber.first_name + ' ' + training.climber.last_name %> </td>
	<td> <%= training.date %> </td>
	<td> <%= training.total %> </td>
	<td> <%= training.top_rope_total %> </td>
	<td> <%= training.boundering_total %> </td>
	<td> <%= link_to 'details', controller: :finishes, action: :index, 
		training_id: training.id %> </td>
	<td> <%= link_to 'edit', edit_training_path(training) if @is_owner %> </td>
	<td> <%= link_to 'delete', training, method: :delete, data: { confirm: 'You sure'} if @is_owner%> </td>
</tr>

app/views/trainings/edit.html.erb
<h1>Edit Training</h1>

<%= render 'form' %>

app/views/trainings/index.html.erb
<%= link_to 'add a new climbing', new_training_path if @is_owner%>

<table class='table'>
  <thead>
    <tr>
    	<th>User</th>
      <th>Date</th>
      <th>Total Finishes</th>
      <th>Top Rope Finishes</th>
      <th>Bouldering Finishes</th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
	  <% @trainings.each do |training| %>
	  	<%= render partial: 'training', locals: {training: training} %>
	  <% end %>
	</tbody>
</table>

app/views/trainings/new.html.erb
<h1>New Training</h1>

<%= render 'form' %>

<!-- # todo: link_to 'view my trainings'