config/routes.rb
Rails.application.routes.draw do

  devise_for :climbers, controllers: { registrations: "climbers/registrations" }

  devise_scope :climber do
    get 'public_climbers' => 'climbers/registrations#public_climbers'
  end

  resources :trainings, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :finishes, only: [:index, :new, :create, :edit, :update, :destroy]

  root 'main#index'
  get 'development' => 'main#development'

end

app/models/finish.rb
class Finish < ActiveRecord::Base
  belongs_to :training

  def climber_id
    training.climber.id
  end
end

app/controllers/finishes_controller.rb
class FinishesController < ApplicationController

	before_action :authenticate_climber!, :except => [:index]

  def index
  	param! :training_id,           Integer, required: true

    authenticate_climber! unless climber_public? Training.climber_id(params[:training_id])

    @is_owner = belong_to_current_user? Training.climber_id(params[:training_id])
    @training = Training.find(params["training_id"])
  	@finishes = @training.finishes.decorate

    respond_to do |format|
      format.html
    end
  end

   def create
    param! :finish, Hash do |t|
      t.param! :catagory , String, required: true
      t.param! :difficulty , String, required: true
      t.param! :value , String, required: true
      t.param! :training_id, Integer, required: true
    end

    @finish = Finish.new(create_finish_params)

    respond_to do |format|
      if @finish.save
        format.html { redirect_to :back }
      else
        format.html { redirect_to :back, notice: 'finish was not successfully created.'  }
      end
    end
  end

  def new
  	@finish = Finish.new
  end

  def edit
    @finish = Finish.find(params[:id])
  end

  def update
    @finish = Finish.find(params[:id])
    respond_to do |format|
      if @finish.update_attributes(update_finish_params)
        format.html { redirect_to finishes_path(training_id: @finish.training_id), notice: 'update success' }
      else
        format.html { redirect_to :back, notice: 'update failed, please try again.' }
      end
    end
  end

  def destroy
    training_id = Finish.find(params[:id]).training_id
    Finish.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'delete success' }
    end
  end

  private 

  def update_finish_params
    params.require(:finish).permit(:catagory, :difficulty, :value)
  end

  def create_finish_params
    params.require(:finish).permit(:catagory, :difficulty, :value,:training_id)
  end

end

app/views/finishes/_finish.html.erb
<tr>
	<td> <%= finish.catagory %> </td>
	<td> <%= finish.difficulty %> </td>
	<td> <%= finish.value %> </td>
	<td> <%= finish.date %> </td>
	<td> <%= link_to 'edit', edit_finish_path(finish) if @is_owner %> </td>
	<td> <%= link_to 'delete', finish, method: :delete, data: { confirm: "You sure?"} if @is_owner %> </td>
</tr>

app/views/finishes/_form.html.erb
<%= form_for(@finish) do |f| %>

  <% if @finish.errors.any? %>
    <div>
      <h2><%= pluralize(@finish.errors.count, "error") %> prohibited this finish from being saved:</h2>
      <ul>
      <% @finish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'type' %><br>
    <%= f.text_field :catagory %>
  </div>

  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.text_field :difficulty %>
  </div>

  <div class="field">
    <%= f.label 'number of finishes' %><br>
    <%= f.number_field :value %>
  </div>

  <%= f.hidden_field :training_id, value: params[:training_id] %>

  <div class="actions">
    <%= f.submit "log this record" %>
  </div>
<% end %>

app/views/finishes/edit.html.erb
<h1>Edit Finish</h1>

<%= render 'form' %>

app/views/finishes/index.html.erb
<table class="table">
  <thead>
    <tr>
    	<th>Type</th>
      <th>Difficulty</th>
      <th>Number of Finishes</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
	  <% @finishes.each do |finish| %>
	  	<%= render partial: 'finish', locals: {finish: finish} %>
	  <% end %>
	</tbody>
</table>

<%= link_to 'back to my climbing logs', trainings_path(climber_id: @training.climber_id) %>

app/views/finishes/new.html.erb
<h1>New Finish</h1>
<%= render 'form' %>
<%= link_to 'view this climbing', 
	finishes_path(training_id: params[:training_id]) %>
<%= link_to 'add another climbing', new_training_path %>